name: dine_here
description: Here comes my Restaurant app.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/welcome.jpeg
    - assets/welcome.png
    - assets/foodie.png
    - assets/pizza.jpeg
    - assets/noodle.jpeg
    - assets/fries.jpeg
    - assets/burger.jpg
